# Generated by Django 2.1 on 2019-06-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=70, unique=True),
        ),
    ]
