# Generated by Django 2.1 on 2019-06-04 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='enroll',
            field=models.ManyToManyField(blank=True, related_name='enrolled_program', to=settings.AUTH_USER_MODEL),
        ),
    ]
