# Generated by Django 2.1 on 2019-06-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20190623_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='english_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
