# Generated by Django 2.1 on 2019-06-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20190604_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_teacher', to='program.Program'),
            preserve_default=False,
        ),
    ]
