# Generated by Django 2.1 on 2019-06-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20190612_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
